In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("home_dataset/HT_Sensor_Dataset.dat", delim_whitespace=True)

In [8]:
df = df.reset_index()
np.random.seed(0)
shuffled = df.reindex(np.random.permutation(df.index))
shuffled = shuffled.drop(["index"], axis=1)

In [10]:
shuffled.to_csv("shuffled_homesensor.csv", index=False)

In [12]:
df.describe()

,index,id,time,R1,R2,R3,R4,R5,R6,R7,R8,Temp.,Humidity
count,928991.0000,928991.000000,928991.000000,928991.000000,928991.000000,928991.000000,928991.000000,928991.000000,928991.000000,928991.000000,928991.000000,928991.000000,928991.000000
mean,464495.0000,49.256372,0.403261,12.185350,8.958396,8.945006,10.130319,15.154167,16.052371,5.390618,5.912815,27.283373,57.568023
std,268176.7463,28.453089,0.859865,0.868116,1.558196,1.748622,1.711879,18.391606,3.303089,2.889244,3.304284,0.904537,4.821784
min,0.0000,0.000000,-0.999999,5.431460,1.820660,1.626900,2.282920,1.901290,5.587950,1.220370,1.430530,24.434400,44.660400
25%,232247.5000,25.000000,-0.320817,11.980000,8.298835,8.273455,9.347275,10.244600,14.780400,4.430490,4.877900,26.764900,53.938100
50%,464495.0000,49.000000,0.366136,12.404700,9.462680,9.564520,10.651800,11.683500,16.521200,5.389800,5.799340,27.328400,57.180800
75%,696742.5000,73.000000,1.055152,12.715500,10.095900,10.207900,11.400000,13.784400,17.353100,5.989300,6.585930,27.868700,60.563500
max,928990.0000,99.000000,3.309882,13.733300,11.315500,11.374200,12.754800,378.750000,73.817800,102.575000,99.888100,30.325400,77.680500